discussion/discussion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

discussion/todolist/urls.py
from django.urls import path

#import the views.py in the same folder
from . import views

app_name = 'todolist'

urlpatterns = [
	path('index', views.index, name = 'index'),
	path('<int:todoitem_id>', views.todoitem, name = 'viewtodoitem'),
	path('register', views.register, name = 'register'),
	path('changepassword', views.change_password, name = "changepassword"),
	path('login', views.login_user, name = "login"),
	path('logout', views.logout_user, name = "logout"),
	path('add_task', views.add_task, name = "add_task"),
	path('<int:todoitem_id>/update_task', views.update_task, name = "update_task"),
	path('<int:todoitem_id>/delete', views.delete_task, name = "deletetask"),
	path('add_event', views.add_event, name = "add_event"),
	path('eventitem/<int:eventitem_id>', views.eventitem, name='vieweventitem'),
	path('<int:eventitem_id>/update_event', views.update_event, name = "update_event")

]

discussion/todolist/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date_created')
	user = models.ForeignKey(User, on_delete = models.RESTRICT, default = "")




class Addevent(models.Model):
    event_name = models.CharField(max_length=200)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete= models.RESTRICT, default = "")




class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

discussion/todolist/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
	username = forms.CharField(label = "username", max_length = 20)
	password = forms.CharField(label = "password", max_length = 20)


class AddTaskForm(forms.Form):
	task_name = forms.CharField(label = "task_name", max_length = 50)
	description = forms.CharField(label = "description", max_length = 50)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label = "task_name", max_length = 50)
	description = forms.CharField(label = "description", max_length = 50)
	status = forms.CharField(label = "status", max_length = 50)


class UpdateEventForm(forms.Form):
	event_name = forms.CharField(label = "event_name", max_length = 50)
	description = forms.CharField(label = "description", max_length = 50)
	status = forms.CharField(label = "status", max_length = 50)


class AddEventForm(forms.Form):
	event_name = forms.CharField(label = "event_name", max_length = 50)
	description = forms.CharField(label = "description", max_length = 50)




class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'confirm_password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and confirm_password and password != confirm_password:
            raise ValidationError("Passwords do not match")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

discussion/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.


# from keyword allows importing of necessary classes/ modules, methos and other files needed in our application from the django.http
from django.http import HttpResponse

# local imports

from .models import ToDoItem, Addevent


from django.contrib.auth.models import User

#import the auth function

from django.contrib.auth import authenticate, login, logout

from django.forms.models import model_to_dict

from .forms import LoginForm, AddTaskForm, UpdateTaskForm, AddEventForm, UpdateEventForm

from django.utils import timezone

# to use templates created

# from django.template import loader


def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id = request.user.id)
	eventitem_list = Addevent.objects.filter(user_id=request.user.id)
	# template = loader.get_template("index.html")
	context = {
		'todoitem_list' : todoitem_list,
		'eventitem_list' : eventitem_list,
		"user": request.user
	}
	# output = ", ".join([todoitem.task_name for todoitem in todoitem_list])


	# render(request, route_template, context)
	return render(request, "index.html", context)


	# return HttpResponse("Hello from the views.py file!")



def todoitem(request, todoitem_id):
	# response = f"You are viewing the details of {todoitem_id}"
	# return HttpResponse(response)

	todoitem = get_object_or_404(ToDoItem, pk = todoitem_id)

	return render(request, "todoitem.html", model_to_dict(todoitem))


# this function is responsible for registering on our application

def register(request):
    if request.method == 'POST':
 
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        
  
        if User.objects.filter(username=username).exists():
            context = {'is_user_registered': True}
            return render(request, 'register.html', context)

   
        if password != confirm_password:
            context = {'passwords_mismatch': True}
            return render(request, 'register.html', context)


        user = User.objects.create_user(username=username, email=email, password=password, first_name=first_name, last_name=last_name)


        user = authenticate(username=username, password=password)
        login(request, user)
        
        return redirect('todolist:index')
        
    else:
        return render(request, 'register.html')





def change_password(request):

	is_user_auth = False

	user = authenticate(username = "johndoe", password = "john123")


	if user is not None:
		authenticated_user = User.objects.get(username = 'johndoe')
		authenticated_user.set_password("john1234")
		authenticated_user.save()

		is_user_auth = True


	context = {
		"is_user_auth" : is_user_auth
	}


	return render(request, "change_password.html", context)




def login_user(request):
	context = {

	}

	# if this is a post request we need to process the form data
	if request.method == "POST":

		form = LoginForm(request.POST)
		if form.is_valid() == False:
			form = LoginForm()
			print(form)
		else:
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			user = authenticate(username = username, password = password)

			if user is not None:
				context = {
					'username' : username,
					'password' : password
				}

				login(request, user)


				return redirect('todolist:index')
			else:
				context = {
					'error' : True
				}	

		
	return render(request, "login.html", context)

	# username = "johndoe"
	# password = 'john1234'

	

	# user = authenticate(username = username, password = password)




def logout_user(request):
	logout(request)
	return redirect("todolist:index")

def add_task(request):
	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			duplicates = ToDoItem.objects.filter(task_name = task_name, user_id = request.user.id)

			if not duplicates:
				# create an object based on the ToDoItem model and saves to the record in the database

				ToDoItem.objects.create(task_name = task_name, description = description, date_created = timezone.now(), user_id = request.user.id)
				return redirect("todolist:index")
			else:
				context = {
					'error' : True
				}
	

	return render(request, "add_task.html", context)




def update_task(request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk = todoitem_id)

	context= {
		"user" : request.user,
		"todoitem_id" : todoitem_id,
		"task_name" : todoitem[0].task_name,
		"description" : todoitem[0].description,
		"status" : todoitem[0].status
	}

	if request.method == "POST":
		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:
			form = UpdateTaskForm()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']


			if todoitem:

				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status


				todoitem[0].save();

				return redirect("todolist:viewtodoitem" , todoitem_id = todoitem[0].id)
			else:

				context = {
					"error" : True
				}


	return render(request, "update_task.html", context)




def delete_task(request, todoitem_id):

	ToDoItem.objects.filter(pk = todoitem_id).delete()


	return redirect("todolist:index")





def add_event(request):
	context = {}

	if request.method == 'POST':
		form = AddEventForm(request.POST)

		if form.is_valid() == False:
			form = AddEventForm()

		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']

			duplicates = Addevent.objects.filter(event_name = event_name, user_id = request.user.id)

			if not duplicates:
				

				Addevent.objects.create(event_name = event_name, description = description, date_created = timezone.now(), user_id = request.user.id)
				return redirect("todolist:index")
			else:
				context = {
					'error' : True
				}
	

	return render(request, "add_event.html", context)


def eventitem(request, eventitem_id):
    eventitem = get_object_or_404(Addevent, pk=eventitem_id)
    return render(request, "eventitem.html", model_to_dict(eventitem))



def update_event(request, eventitem_id):

	eventitem = Addevent.objects.filter(pk = eventitem_id)

	context= {
		"user" : request.user,
		"eventitem_id" : eventitem_id,
		"event_name" : eventitem[0].event_name,
		"description" : eventitem[0].description,
		"status" : eventitem[0].status
	}

	if request.method == "POST":
		form = UpdateEventForm(request.POST)

		if form.is_valid() == False:
			form = UpdateEventForm()

		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']


			if eventitem:

				eventitem[0].event_name = event_name
				eventitem[0].description = description
				eventitem[0].status = status


				eventitem[0].save();

				return redirect("todolist:vieweventitem" , eventitem_id = eventitem[0].id)
			else:

				context = {
					"error" : True
				}


	return render(request, "update_event.html", context)

discussion/todolist/templates/add_event.html
{%  extends 'base.html'%}



{% block title%} Add Event {%endblock%}


{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">


					{% if error == True %}
      		<p class="text-danger">Duplicate list</p>
      	{% endif %}

				<form action="{% url 'todolist:add_event' %}" method="POST">
                        {% csrf_token %}
                            
                        <div class="mb-3">
                            <label for="event_name">Event Name: </label>
                            <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="description">Description: </label>
                            <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
                        </div>

                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Add Event">
                        </div>

                    </form>



			</div>
		</div>
	</div>








{% endblock %}

discussion/todolist/templates/add_task.html
{%  extends 'base.html'%}



{% block title%} Add Task {%endblock%}


{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">


					{% if error == True %}
      		<p class="text-danger">Duplicate list</p>
      	{% endif %}

				<form action="{% url 'todolist:add_task' %}" method="POST">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="task_name">Task Name: </label>
                            <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="description">Description: </label>
                            <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
                        </div>

                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Add Task">
                        </div>

                    </form>



			</div>
		</div>
	</div>








{% endblock %}

discussion/todolist/templates/change_password.html
{% if is_user_auth == False %}
	<h1>invalid user credential!</h1>
	<p>check if the username and password is correct</p>


{% else %}
	<h1>User password successfully updated!</h1>
	<p>the password has ben successfully updated</p>




{% endif%}

discussion/todolist/templates/eventitem.html
{% extends 'base.html' %}


{% block title %}Event{% endblock%}

{%block content%}
<div class="text-center mt-3">
<h1>{{event_name}}</h1>
<h3>Description:</h3>
<p>{{description}}</p>
<h3>Status:</h3>
<p>{{status}}</p>


<button class="btn btn-success mx-1">
<a class="text-decoration-none text-light" href="{%url 'todolist:update_event' id %}">Edit Event</a>
</button>

<button class="btn btn-danger mx-1">
<a class="text-decoration-none text-light" href="">Delete</a>
</button>

<button class="btn btn-warning mx-1">
<a class="text-decoration-none" href="{% url 'todolist:index'%}">Back</a>
</button>
</div>


{%endblock%}

discussion/todolist/templates/index.html
{% extends 'base.html' %}

{%block title%} Home {%endblock%}

{%block content%}
{%  if todoitem_list and user.is_anonymous == False %}
 <h1 class="text-center my-3">Welcome {{user.first_name}} {{user.last_name}}</h1>
 
 <div class="container">
 	<div class="row">
 		<h3 class="text-center mb-3">My Tasks</h3>
 <ul class=" list-group text-center col-lg-4 offset-lg-4">
	{% for todoitem in todoitem_list %}
		<li class = "list-group-item"><a class = "text-decoration-none"href = "{% url 'todolist:viewtodoitem' todoitem.id %}">{{todoitem.task_name}}</a></li>
				{% endfor%}

	</ul>

 	</div>
</div>


<div class="container">
 	<div class="row">
 		<h3 class="text-center mb-3">My Events</h3>
 <ul class="list-group text-center col-lg-4 offset-lg-4">
    {% for eventitem in eventitem_list %}
    <li class="list-group-item"><a class="text-decoration-none" href="{% url 'todolist:vieweventitem' eventitem.id %}">{{ eventitem.event_name }}</a></li>
    {% endfor %}
</ul>


 	</div>
</div>


 

{%elif todoitem_list.count == 0 and user.is_anonymous == False %}
	<h1>Welcome {{user.first_name}} {{user.last_name}}</h1>
	<p>No tasks have been created</p>

{%else%}
  <h1 class="text-center my-3">You are not authorized to access this page.</h1>
  <p class="text-center my-3">Kindly login <a href = "{% url 'todolist:login' %}">here</a>.</p>





{%endif%}

{%endblock%}




<!-- {% if todoitem_list %}
	<ul>
	{% for todoitem in todoitem_list %}
		<li><a href="{{todoitem.id}}">{{todoitem.task_name}}</a></li>
	{% endfor%}
	</ul>

{% else %}
	<p>No tasks have been created.</p>


{% endif %} -->


<!-- {%  if todoitem_list and user.is_anonymous == False %}
 <h1>Welcome {{user.first_name}} {{user.last_name}}</h1>
 <ul>
	{% for todoitem in todoitem_list %}
		<li><a href="{{todoitem.id}}">{{todoitem.task_name}}</a></li>
	{% endfor%}
	</ul>

{%elif todoitem_list.count == 0 and user.is_anonymous == False %}
	<h1>Welcome {{user.first_name}} {{user.last_name}}</h1>
	<p>No tasks have been created</p>

{%else%}
  <h1>You are not authorized to access this page.</h1>
  <p>Kindly <a href="login">login</a></p>





{%endif%}
	 -->

discussion/todolist/templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
  <h1 class="text-center my-3"> Login Form</h1>

  <div class="container">
    <div class="row">
      <div class="col-6 offset-3">


      	{% if error == True %}
      		<p class="text-danger">Invalid credentials, Please check your username and password or register</p>
      	{% endif %}
        <form action="{% url 'todolist:login' %}" method="POST">
          {% csrf_token %}
          <div class="mb-3">
            <label for="username" class="form-label">Username:</label>
            <input type="text" class="form-control" id="username" value="{{ username }}" name="username" maxlength="20">
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password:</label>
            <input type="password" class="form-control" id="password" name="password" value="{{ password }}" maxlength="20" required>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

discussion/todolist/templates/register.html
{%  extends 'base.html'%}



{% block title%} Register {%endblock%}


{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">


					{% if error == True %}
      		<p class="text-danger">Duplicate User</p>
      	{% endif %}

				<form action="{% url 'todolist:register' %}" method="POST">
                        {% csrf_token %}
                        	<h1 class="text-center">Registration</h1>
                        <div class="mb-3">
                            <label for="username">UserName: </label>
                            <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="firstname">Firstname: </label>
                            <input class="form-control" name="first_name"  value="{{ firstname }}" required>
                        </div>

                          <div class="mb-3">
                            <label for="lastname">Lastname: </label>
                            <input class="form-control" name="last_name" value="{{ lastname }}" required>
                        </div>

                          <div class="mb-3">
                            <label for="email">Email: </label>
                            <input class="form-control" name="email" value="{{ email }}" required>
                        </div>

                          <div class="mb-3">
                            <label for="password">Password: </label>
                            <input class="form-control" name="password" type="password" value="{{ password }}" required>
                        </div>

                          <div class="mb-3">
                            <label for="password1">Confirm Password: </label>
                            <input class="form-control" name="confirm_password" type="password" value="{{ password1 }}" required>
                        </div>

                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Register">
                        </div>

                    </form>



			</div>
		</div>
	</div>








{% endblock %}

discussion/todolist/templates/todoitem.html
{% extends 'base.html' %}


{% block title %}Task{% endblock%}

{%block content%}
<div class="text-center mt-3">
<h1>{{task_name}}</h1>
<h3>Description:</h3>
<p>{{description}}</p>
<h3>Status:</h3>
<p>{{status}}</p>


<button class="btn btn-success mx-1">
<a class="text-decoration-none text-light" href="{% url 'todolist:update_task' id %}">Edit task</a>
</button>

<button class="btn btn-danger mx-1">
<a class="text-decoration-none text-light" href="{% url 'todolist:deletetask' id %}">Delete</a>
</button>

<button class="btn btn-warning mx-1">
<a class="text-decoration-none" href="{% url 'todolist:index'%}">Back</a>
</button>
</div>


{%endblock%}
<!-- <h1>{{task_name}}</h1>
<h3>Description:</h3>
<p>{{description}}</p>
<h3>Status:</h3>
<p>{{status}}</p>



<a href="{% url 'todolist:index'%}">Back to index page!</a> -->

discussion/todolist/templates/update_event.html
{% extends 'base.html' %}



{% block title %}Update Event{% endblock%}




{%block content%}
		{% if user.is_anonymous == False%}
			<div class="container">
				<div class="row">
					<div class="col-6 offset-3">
						<h1 class="text-center mt-3">Update Event</h1>


						{% if error == True%}
							<p class="text-danger text-center">Event Not Found</p>
						{%endif%}

						<form action="{% url 'todolist:update_event' eventitem_id %}" method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="event_name">Event Name: </label>
                            <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="description">Description: </label>
                            <textarea class="form-control" name="description" required>{{ description }}</textarea>
                        </div>

                        <div class="mb-3">
                            <label for="status">Status: </label>
                            <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
                        </div>

                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Update Event">
                        </div>

                    </form>


					</div>

				</div>


			</div>
		{% endif%}


{%endblock%}

discussion/todolist/templates/update_task.html
{% extends 'base.html' %}



{% block title %}Update Task{% endblock%}




{%block content%}
		{% if user.is_anonymous == False%}
			<div class="container">
				<div class="row">
					<div class="col-6 offset-3">
						<h1 class="text-center mt-3">Update Task</h1>


						{% if error == True%}
							<p class="text-danger text-center">Task Not Found</p>
						{%endif%}

						<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="task_name">Task Name: </label>
                            <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="description">Description: </label>
                            <textarea class="form-control" name="description" required>{{ description }}</textarea>
                        </div>

                        <div class="mb-3">
                            <label for="status">Status: </label>
                            <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
                        </div>

                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Update Task">
                        </div>

                    </form>


					</div>

				</div>


			</div>
		{% endif%}


{%endblock%}